### ISSUE TITLE
UnboundLocalError: local variable 'displayo' referenced before assign

### ISSUE THREAD

**Issue by yoavram** [wooey/Wooey#4]
I get it for any script I run.
Windows 7 64 bit, Python 2.7.

**Comment by mfitzp** [comment]
Thanks for the bugreport @yoavram this should be fixed in the latest release (and packaged on PyPi as v0.0.3). Let me know if you have any more problems.

**Comment by yoavram** [comment]
I did a `git pull` to update, verified the version:
```
> python -c "import wooey; print wooey.__version__"
0.0.3
```
I start wooey and still get the error:
```
09:19:28 web.1    | INFO:werkzeug:127.0.0.1 - - [02/Apr/2015 09:19:28] "GET /jobs/3.json HTTP/1.1" 500 -
09:19:30 web.1    | Traceback (most recent call last):
09:19:30 worker.1 | INFO:root:Shutting down...
09:19:30 web.1    |   File "D:\workspace\Wooey\venv\lib\site-packages\flask\app.py", line 1836, in __call__
09:19:30 worker.1 | INFO:root:Done.
09:19:30 web.1    |     return self.wsgi_app(environ, start_response)
09:19:30 web.1    |   File "D:\workspace\Wooey\venv\lib\site-packages\flask\app.py", line 1820, in wsgi_app
09:19:30 web.1    |     response = self.make_response(self.handle_exception(e))
09:19:30 web.1    |   File "D:\workspace\Wooey\venv\lib\site-packages\flask\app.py", line 1403, in handle_exception
09:19:30 web.1    |     reraise(exc_type, exc_value, tb)
09:19:30 web.1    |   File "D:\workspace\Wooey\venv\lib\site-packages\flask\app.py", line 1817, in wsgi_app
09:19:30 web.1    |     response = self.full_dispatch_request()
09:19:30 web.1    |   File "D:\workspace\Wooey\venv\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
09:19:30 web.1    |     rv = self.handle_user_exception(e)
09:19:30 web.1    |   File "D:\workspace\Wooey\venv\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
09:19:30 web.1    |     reraise(exc_type, exc_value, tb)
09:19:30 web.1    |   File "D:\workspace\Wooey\venv\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
09:19:30 web.1    |     rv = self.dispatch_request()
09:19:30 web.1    |   File "D:\workspace\Wooey\venv\lib\site-packages\flask\app.py", line 1461, in dispatch_request
09:19:30 web.1    |     return self.view_functions[rule.endpoint](**req.view_args)
09:19:30 web.1    |   File "D:\workspace\Wooey\wooey\public\views.py", line 277, in job_json
09:19:30 web.1    |     for section, oo in displayo.items():
09:19:30 web.1    | UnboundLocalError: local variable 'displayo' referenced before assignment
```

**Comment by mfitzp** [comment]
That's not a surprise, since I accidentally managed to commit the version bump but not the change!? I've fixed it now and uploaded/released as 0.0.4. I'll wait for your confirmation to close, in case I'm being daft again.

**Comment by yoavram** [comment]
It's fixed, but now I get
```
INFO:root:Starting job 5.
16:48:49 worker.1 | ERROR:root:
16:48:52 web.1    | INFO:werkzeug:127.0.0.1 - - [05/Apr/2015 16:48:52] "GET /jobs/5.json HTTP/1.1" 200 -
```

**Comment by mfitzp** [comment]
How are you attempting to run Wooey? (It looks like it might be Heroku which currently doesn't work as we need persistent storage. Working on a way around this...)

If not ...
How does it look on the web side? Do you see output? Logging errors firing on the worker may just be the scripts failing during to incorrect input.

**Comment by yoavram** [comment]
I'm running locally with `foreman start` and a `Procfile` that starts the web and worker processes. Like a local Heroku setup - that's why it looks like I'm on Heroku.

I've now tried without `foreman` - just starting the server from one console and the daemon from another. On the daemon console I get:
```
(venv) D:\workspace\Wooey>python manage.py start_daemon
INFO:root:Starting job 6.
ERROR:root:
```
On the server I get alot of
```
INFO:werkzeug:127.0.0.1 - - [05/Apr/2015 23:42:16] "GET /jobs/6.json HTTP/1.1" 200 -
```
The browser console is empty. The queue tab shows the job with an Error status.

**Comment by mfitzp** [comment]
When you run `python manage.py start_daemon` does it exit after the error, or just sit there quietly? If the latter that means that the job in the queue has errored. What happens if you submit a new job (via the web UI)? There should normally be more output for that though. 

If not (and it's crashing) that's definitely not supposed to happen. The server output is normal, but are there multiple requests to the `6.json` file? Errors shouldn't be attempting to refresh either. Hm.

**Comment by yoavram** [comment]
Its sits there quietly.
If I submit a new job the same thing happens again.
There are multiple requests to the json file, one every few seconds.

**Comment by mfitzp** [comment]
Thanks, that's a bit odd. I'll have a look and see if I can tell what is happening. Which script are you trying to run, one of the included demo scripts or a custom one?

If the script errors the status should be updated and the refresh cancelled.

**Comment by yoavram** [comment]
Two of the included - the plot numbers one and the one that needs the data file.

I didn't understand the second paragraph of your last comment.

**Comment by mfitzp** [comment]
In bug #7 a similar "job starting, but not doing anything" error has been reported after copy-pasting the demo code to a new file. I think it's possible that the script being run is not executable (this will be required on Linux or Mac).

    chmod +x your_script_here.py

Let me know if that helps!

**Comment by yoavram** [comment]
As the original post says, I'm using Windows 7 64 bit, so not sure if `chmod +x` has anything to do with it...

**Comment by mfitzp** [comment]
My apologies I missed that. But it’s actually a related problem: on Windows you need to specify the interpreter `python` to execute a script as there is no equivalent of the shebang. Wooey doesn’t support this at present (it attempts to runs the script directly) from the command line. Simple fix to add support for specifying an interpreter in the admin, will get it done.

On 10 May 2015 at 16:09:49, Yoav Ram (notifications@github.com) wrote:

As the original post says, I'm using Windows 7 64 bit, so not sure if chmod +x has anything to do with it...

**Comment by yoavram** [comment]
Great, update me when ready and I'll test it again. Thanks.

**Comment by mfitzp** [comment]
Merged wooey+djangui project now has a different internal structure so this code no longer exists. Feel free to test the new version however! Thanks.
